### ISSUE TITLE
BUG - Empty Space opens browser window when clicked

### ISSUE THREAD

**Issue by Myke500** [stakecube/stakecubecoin-archive#14]
Found an area on the wallet that will trigger a browser window to open when clicked on.  

It will send the browser to this link [http://209.250.224.166/img/?url=52707640]  The link does not resolve.

![image](https://user-images.githubusercontent.com/17334141/74097520-a70cd100-4ac1-11ea-9a29-2ad56209b3c8.png)

__**Reproduce:**__

**NOTE** (This assumes a previous version of SCC was already installed)

**Environment:**

- Windows 64
- StakeCubeCore version v1.0.0.2-944a15df8-dirty (64-bit)
Chrome Browser

     1. Install StakeCubeCore.exe v1.0.0.2  for windows 64bit
     2. Run File
     3. Once the UI is loaded this area becomes active when clicked and triggers the browser to open the link above.

**Comment by stakecube** [comment]
Price display will be removed with PR #10
